#para rutas front
actividadacademicadetalle:
    path:      /actividadacademicadetalle/{page}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    requirements:
        page: \d+|new
    options:
        expose: true
#rutas del back o api         
actividadacademicadetalle_api:
    type: rest
    resource: "@MultiacademicoBundle/Controller/ActividadAcademicaDetalleController.php"
    options:
        expose: true
    prefix: api 
actividadacademicadetalle_results:
    path:     /actividadacademicadetalle/results
    defaults: { _controller: "MultiacademicoBundle:ActividadAcademicaDetalle:results" }
    methods:  [GET, POST]
actividadacademicadetalle_edit:
    path:     /actividadacademicadetalle/{page}/edit
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    methods:  [GET, POST]
    options:
        expose: true
