#para rutas front
actividadacademica:
    path:      /actividadacademica/{page}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    requirements:
        page: \d+|new
    options:
        expose: true
#rutas del back o api         
actividadacademica_api:
    type: rest
    resource: "@MultiacademicoBundle/Controller/ActividadAcademicaController.php"
    options:
        expose: true
    prefix: api 
actividadacademica_results:
    path:     /actividadacademica/results
    defaults: { _controller: "MultiacademicoBundle:ActividadAcademica:results" }
    methods:  [GET, POST]
actividadacademica_edit:
    path:     /actividadacademica/{page}/edit
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    methods:  [GET, POST]
    options:
        expose: true
actividadacademica_detalle:
    path:     /actividadacademica/{page}/detalle/{detail}
    defaults:  { _controller: AppBundle:Default:inicio, page: index, detail: detail }
    methods:  [GET]
