#para rutas front
areaacademica:
    path:      /areaacademica/{page}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    requirements:
        page: \d+|new
    options:
        expose: true
#rutas del back o api         
areaacademica_api:
    type: rest
    resource: "@MultiacademicoBundle/Controller/AreaAcademicaController.php"
    options:
        expose: true
    prefix: api 
areaacademica_results:
    path:     /areaacademica/results
    defaults: { _controller: "MultiacademicoBundle:AreaAcademica:results" }
    methods:  [GET, POST]
areaacademica_edit:
    path:     /areaacademica/{page}/edit
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    methods:  [GET, POST]
    options:
        expose: true
