#para rutas front
asistencia:
    path:      /asistencia/{page}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    requirements:
        page: \d+|new
    options:
        expose: true
#rutas del back o api         
asistencia_api:
    type: rest
    resource: "@MultiacademicoBundle/Controller/AsistenciaController.php"
    options:
        expose: true
    prefix: api 
asistencia_results:
    path:     /asistencia/results
    defaults: { _controller: "MultiacademicoBundle:Asistencia:results" }
    methods:  [GET, POST]
asistencia_edit:
    path:     /asistencia/{page}/edit
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    methods:  [GET, POST]
    options:
        expose: true
