#para rutas front
aulas:
    path:      /aulas/{page}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    requirements:
         page: ".*"
    options:
        expose: true     
aulasapi:
    type: rest
    resource: MultiacademicoBundle\Controller\AulasController
    options:
        expose: true
    prefix: api
aulas_results:
    path:     /aulas/results
    defaults: { _controller: "MultiacademicoBundle:Aula:results" }
    methods:  [GET, POST]
aulas_edit:
    path:     /aulas/{curso}/{especializacion}/{paralelo}/{seccion}/{periodo}/edit
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    methods:  [GET, POST]
    options:
        expose: true
aulas_show:
    path:     /aulas/{curso}/{especializacion}/{paralelo}/{seccion}/{periodo}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    methods:  [GET]
    options:
        expose: true