#para rutas front
comportamiento:
    path:      /comportamiento/{page}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    requirements:
        page: \d+|new
    options:
        expose: true
#rutas del back o api         
comportamiento_api:
    type: rest
    resource: "@MultiacademicoBundle/Controller/ComportamientoController.php"
    options:
        expose: true
    prefix: api 
comportamiento_results:
    path:     /comportamiento/results
    defaults: { _controller: "MultiacademicoBundle:Comportamiento:results" }
    methods:  [GET, POST]
comportamiento_edit:
    path:     /comportamiento/{page}/edit
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    methods:  [GET, POST]
    options:
        expose: true
