#para rutas front
entidad:
    path:      /entidad/{page}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    requirements:
        page: \d+|new
    options:
        expose: true
#rutas del back o api         
entidad_api:
    type: rest
    resource: "@MultiacademicoBundle/Controller/EntidadController.php"
    options:
        expose: true
    prefix: api 
entidad_results:
    path:     /entidad/results
    defaults: { _controller: "MultiacademicoBundle:Entidad:results" }
    methods:  [GET, POST]
entidad_edit:
    path:     /entidad/{page}/edit
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    methods:  [GET, POST]
    options:
        expose: true
