#para rutas front
matriculas:
    path:      /matriculas/{page}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    requirements:
        page: \d+|new
    options:
        expose: true
#rutas del back o api         
matriculas_api:
    type: rest
    resource: "@MultiacademicoBundle/Controller/MatriculasController.php"
    options:
        expose: true
    prefix: api 
matriculas_results:
    path:     /matriculas/results
    defaults: { _controller: "MultiacademicoBundle:Matriculas:results" }
    methods:  [GET, POST]
matriculas_edit:
    path:     /matriculas/{page}/edit
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    methods:  [GET, POST]
    options:
        expose: true
