#para rutas front
pension:
    path:      /pensiones/{page}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    requirements:
        page: \d+|new|aulas
    options:
        expose: true
#rutas del back o api         
pension_api:
    type: rest
    resource: "@MultiacademicoBundle/Controller/PensionController.php"
    options:
        expose: true
    prefix: api 
pension_results:
    path:     /pension/results
    defaults: { _controller: "MultiacademicoBundle:Pension:results" }
    methods:  [GET, POST]
pension_edit:
    path:     /pension/{page}/edit
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    methods:  [GET, POST]
    options:
        expose: true
pension_pay:
    path:     /pension/{page}/pay
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    methods:  [PUT]
    options:
        expose: true        
#ruta para txtbanco
pensiones_download:
    path:      /pensiones/download/{seccion}
    defaults:  { _controller: MultiacademicoBundle:Pensiones:download, seccion: all}        
