#para rutas front
representantes:
    path:      /representantes/{page}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    requirements:
        page: \d+|new
    options:
        expose: true
#rutas del back o api         
representantes_api:
    type: rest
    resource: "@MultiacademicoBundle/Controller/RepresentantesController.php"
    options:
        expose: true
    prefix: api 
representantes_results:
    path:     /representantes/results
    defaults: { _controller: "MultiacademicoBundle:Representantes:results" }
    methods:  [GET, POST]
representantes_edit:
    path:     /representantes/{page}/edit
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    methods:  [GET, POST]
    options:
        expose: true
