imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
 #   - { resource: redis.yml }  
    - { resource: types.yml }  

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_horizontal_layout.html.twig'
    globals:
        entidad: '@entidadData'
    #form_themes:
        #- 'AppBundle:Form:fields.html.twig'
        #- 'MultiservicesArxisBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: '%kernel.debug%'
    #use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        vendor-ui:
            inputs: 
                - %kernel.root_dir%/../web/build/vendor.ui.js
            output: build/vendor.ui.js
        vendor-datatables:
            inputs: 
                - %kernel.root_dir%/../web/build/vendor.datatables.js
            output: build/vendor.datatables.js
        blankon_css:
            inputs:
                - %kernel.root_dir%/../web/app/styles/reset.css
                - %kernel.root_dir%/../web/app/styles/layout.css
                - %kernel.root_dir%/../web/app/styles/components.css
                - %kernel.root_dir%/../web/app/styles/plugins.css
                - %kernel.root_dir%/../web/app/styles/custom.css
            output: css/compiled/rlcpc.css
        error404_css:
            inputs:
                - %kernel.root_dir%/../web/app/styles/pages/error-page.css
            output: app/styles/pages/error-page.css
        xeditable_css:
            inputs:
                - %kernel.root_dir%/../web/plugin/angular-xeditable/dist/css/xeditable.css
            output: plugin/angular-xeditable/dist/css/xeditable.css  
        bootstrapinputcss:
            inputs:
            - %kernel.root_dir%/../web/plugin/bootstrap-tagsinput/dist/bootstrap-tagsinput.css
            output: plugin/bootstrap-tagsinput/dist/bootstrap-tagsinput.css
        jasny-bootstrapcss:
            inputs:
            - %kernel.root_dir%/../web/plugin/jasny-bootstrap-fileinput/css/jasny-bootstrap-fileinput.min.css
            output: plugin/jasny-bootstrap-fileinput/css/jasny-bootstrap-fileinput.min.css
        chosen120css:
            inputs:
            - %kernel.root_dir%/../web/plugin/chosen_v1.2.0/chosen.min.css
            output: plugin/chosen_v1.2.0/chosen.min.css
        theme_blue_css:
            inputs:
                - %kernel.root_dir%/../web/app/styles/themes/blue.theme.css
            output: css/compiled/blue.theme.css
        angular_custom_css:
            inputs:
                - %kernel.root_dir%/../web/app/styles/angular-custom.css    
            output: css/compiled/angular-custom.css
        #dropzone_css:
        #    inputs:
        #        - %kernel.root_dir%/../web/vendor/dropzone/dist/min/dropzone.min.css 
        #    output: vendor/dropzone/dist/min/dropzone.min.css  
        griter_img:
            inputs:
                - %kernel.root_dir%/../web/plugin/jquery.gritter/images/gritter.png
            output: plugin/jquery.gritter/images/gritter.png 
        griter_img1:
            inputs:
                - %kernel.root_dir%/../web/plugin/jquery.gritter/images/ie-spacer.gif
            output: plugin/jquery.gritter/images/ie-spacer.gif
        griter_css:
            inputs:
                - %kernel.root_dir%/../web/plugin/jquery.gritter/css/jquery.gritter.css 
            output: plugin/jquery.gritter/css/jquery.gritter.css     
        
        chosen_css:
            inputs:
                - %kernel.root_dir%/../web/plugin/chosen/chosen.min.css 
            output: plugin/chosen/chosen.min.css    
        chosen_sprite_png:
            inputs:
                - %kernel.root_dir%/../web/plugin/chosen/chosen-sprite.png 
            output: plugin/chosen/chosen-sprite.png     
        sign_css:
            inputs:
                - %kernel.root_dir%/../web/app/styles/pages/sign.css    
            output: css/compiled/pages/sign.css
        beer_can_opening_mp3:
            inputs:
                - %kernel.root_dir%/../web/assets/global/plugins/bower_components/ionsound/sounds/beer_can_opening.mp3
            output: sounds/beer_can_opening.mp3
        bell_ring_mp3:
            inputs:
                - %kernel.root_dir%/../web/assets/global/plugins/bower_components/ionsound/sounds/bell_ring.mp3
            output: sounds/bell_ring.mp3
        button_click_mp3:
            inputs:
                - %kernel.root_dir%/../web/assets/global/plugins/bower_components/ionsound/sounds/button_click.mp3
            output: sounds/button_click.mp3    
        notifications_json:
            inputs:
                - %kernel.root_dir%/../web/data/partials/header/navbar-notifications.json
            output: data/partials/header/navbar-notifications.json
        messajes_json:
            inputs:
                - %kernel.root_dir%/../web/data/partials/header/navbar-messages.json 
            output: data/partials/header/navbar-messages.json 
        color_json:
            inputs:
                - %kernel.root_dir%/../web/data/views/tables/color.json 
            output: data/views/tables/color.json 
        chat_json:
            inputs:
                - %kernel.root_dir%/../web/data/partials/sidebar-right/chat.json
            output: data/partials/sidebar-right/chat.json    
        profile_json:    
            inputs:
                - %kernel.root_dir%/../web/data/partials/sidebar-right/profile.json
            output: data/partials/sidebar-right/profile.json
        dashboardhtml:    
            inputs:
                - %kernel.root_dir%/../web/views/dashboard.html
            output: /views/dashboard.html
        matriculashtml:    
            inputs:
                - %kernel.root_dir%/../web/views/matriculas.html
            output: /views/matriculas.html
        seleccionaraulamallasnormalhtml:
            inputs:
                -  %kernel.root_dir%/../web/views/multiacademico/malla/seleccionar-aula-malla-normal.html
            output: /views/multiacademico/malla/seleccionar-aula-malla-normal.html 
        seleccionaraulainformeshtml:
            inputs:
                -  %kernel.root_dir%/../web/views/multiacademico/informes/seleccionar-aula-informes.html
            output: /views/multiacademico/informes/seleccionar-aula-informes.html
        seleccionaraulacertificadomatriculahtml:
            inputs:
                -  %kernel.root_dir%/../web/views/multiacademico/certificados/seleccionar-aula-certificado-matricula.html
            output: /views/multiacademico/certificados/seleccionar-aula-certificado-matricula.html
        seleccionaraulacertificadopromocionhtml:
            inputs:
                -  %kernel.root_dir%/../web/views/multiacademico/certificados/seleccionar-aula-certificado-promocion.html
            output: /views/multiacademico/certificados/seleccionar-aula-certificado-promocion.html    
        menucalificacionesedtudianteshtml:
            inputs:
                -  %kernel.root_dir%/../web/views/multiacademico/estudiantes/menu-calificaciones.html
            output: /views/multiacademico/estudiantes/menu-calificaciones.html
        
        comportamientohtml:
            inputs:
                -  %kernel.root_dir%/../web/views/multiacademico/malla/comportamiento.html
            output: /views/multiacademico/malla/comportamiento.html
        
        dosquimestrehtml:
            inputs:
                -  %kernel.root_dir%/../web/views/multiacademico/malla/dos-quimestre.html
            output: /views/multiacademico/malla/dos-quimestre.html
        error404_html:
            inputs:
                - %kernel.root_dir%/../web/views/pages/page-error-404.html
            output: views/pages/page-error-404.html

            
            
                
            
            

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        #metadata_cache_driver: redis
        #query_cache_driver: redis
        #result_cache_driver: redis
        # entity_managers:
        #     default:
        #         mappings:
        #             VNNCoreBundle: ~
        #             VNNPressboxBundle: ~
        #second_level_cache:
        #    enabled: true

cspoo_swiftmailer_mailgun:
    key: "%mailgun_key%"
    
    domain: "multiacademico.com"
    http_client: 'httplug.client'

# Swiftmailer Configuration
swiftmailer:
    default_mailer: mailgun_mailer
    mailers:
        normal_mailer:
            host:      "%mailer_host%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            port: %mailer_port%
            encryption: %mailer_encryption%
            spool:     { type: memory }
        mailgun_mailer:
            transport: mailgun
            spool:     { type: memory }
    
# Nelmio CORS
nelmio_cors:
    defaults:
        allow_origin:  ["multiacademico.com"]
        allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
        allow_headers: ["content-type", "authorization"]
        max_age:       3600
    paths:
        '^/': ~    
    
knp_snappy:
    temporary_folder: %kernel.cache_dir%/snappy
    pdf:
        enabled:    true
        binary:     %kernel.root_dir%/../vendor/bin/wkhtmltopdf64
        #binary:     "%pdf_generator%"
        options:    []
    #image:
        #enabled:    true
        #binary:     /usr/local/bin/wkhtmltoimage #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" for Windows users
        #options:    []    
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Multiservices\ArxisBundle\Entity\Usuario
    from_email:
        address:        info@multiacademico.com
        sender_name:    Multiacademico App
    resetting:
        email:
            from_email:
                address:        info@multiacademico.com
                sender_name:    Multiacademico App
    registration:
        confirmation:
            enabled: true
        form:
            type: app_user_registration
    group:
        group_class: Multiservices\ArxisBundle\Entity\Grupo
sensio_framework_extra:
    view:
        annotations: false
fos_rest:
    param_fetcher_listener: true
    body_listener: true
          
    view:
        view_response_listener:
            enabled:              true
            force:                false
        serialize_null:       false
    serializer:
        serialize_null:       false   
fos_oauth_server:
    db_driver: orm       
    client_class:        AppBundle\Entity\Client
    access_token_class:  AppBundle\Entity\AccessToken
    refresh_token_class: AppBundle\Entity\RefreshToken
    auth_code_class:     AppBundle\Entity\AuthCode  
    service:
        user_provider: fos_user.user_provider.username
hwi_oauth:
    connect:
        account_connector: my_user_provider
    firewall_names: [main]
    # optional FOSUserBundle integration
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            #facebook: facebook_id
            #google: google_id
            multiacademico: username
    resource_owners:
        multiacademico:
            type:                oauth2
            client_id:           %oauth_client%
            client_secret:       %oauth_secret%
            access_token_url:    %website_back_base_url%/oauth/v2/token
            authorization_url:   %website_back_base_url%/oauth/v2/auth
            infos_url:           %website_back_base_url%/me
            #scope:               "read"
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
            options:
                csrf: true
            paths:
                identifier: id
                nickname:   username
                password:   password
                realname:   username
kreait_firebase:
  connections:
    main:
      scheme: https
      #host: %firebase_host%
      #service_account: %firebase_service_json%
      host: multiacademico-test.firebaseio.com
      service_account: %kernel.root_dir%/Resources/FireBase/MultiacademicoTest-3fe0ede53e47.json
      