imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: types.yml }  

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_horizontal_layout.html.twig']
    #form_themes:
        #- 'AppBundle:Form:fields.html.twig'
        #- 'MultiservicesArxisBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        main_css:
            inputs:
                - %kernel.root_dir%/../web/app/styles/main.css
            output: css/compiled/main.css
        blankon_css:
            inputs:
                - %kernel.root_dir%/../web/app/styles/reset.css
                - %kernel.root_dir%/../web/app/styles/layout.css
                - %kernel.root_dir%/../web/app/styles/components.css
                - %kernel.root_dir%/../web/app/styles/plugins.css
                - %kernel.root_dir%/../web/app/styles/custom.css
            output: css/compiled/rlcpc.css
        theme_blue_css:
            inputs:
                - %kernel.root_dir%/../web/app/styles/themes/blue.theme.css
            output: css/compiled/blue.theme.css
        angular_custom_css:
            inputs:
                - %kernel.root_dir%/../web/app/styles/angular-custom.css    
            output: css/compiled/angular-custom.css
        dropzone_css:
            inputs:
                - %kernel.root_dir%/../web/vendor/dropzone/dist/min/dropzone.min.css 
            output: vendor/dropzone/dist/min/dropzone.min.css  
        griter_css:
            inputs:
                - %kernel.root_dir%/../web/vendor/jquery.gritter/css/jquery.gritter.css 
            output: vendor/jquery.gritter/css/jquery.gritter.css 
        chosen_css:
            inputs:
                - %kernel.root_dir%/../web/vendor/chosen/chosen.min.css 
            output: vendor/chosen/chosen.min.css    
        chosen_sprite_png:
            inputs:
                - %kernel.root_dir%/../web/vendor/chosen/chosen-sprite.png 
            output: vendor/chosen/chosen-sprite.png     
        sign_css:
            inputs:
                - %kernel.root_dir%/../web/app/styles/pages/sign.css    
            output: css/compiled/pages/sign.css
        beer_can_opening_mp3:
            inputs:
                - %kernel.root_dir%/../web/assets/global/plugins/bower_components/ionsound/sounds/beer_can_opening.mp3
            output: sounds/beer_can_opening.mp3
        bell_ring_mp3:
            inputs:
                - %kernel.root_dir%/../web/assets/global/plugins/bower_components/ionsound/sounds/bell_ring.mp3
            output: sounds/bell_ring.mp3
        button_click_mp3:
            inputs:
                - %kernel.root_dir%/../web/assets/global/plugins/bower_components/ionsound/sounds/button_click.mp3
            output: sounds/button_click.mp3    
        notifications_json:
            inputs:
                - %kernel.root_dir%/../web/data/partials/header/navbar-notifications.json
            output: data/partials/header/navbar-notifications.json
        messajes_json:
            inputs:
                - %kernel.root_dir%/../web/data/partials/header/navbar-messages.json 
            output: data/partials/header/navbar-messages.json 
        color_json:
            inputs:
                - %kernel.root_dir%/../web/data/views/tables/color.json 
            output: data/views/tables/color.json 
        chat_json:
            inputs:
                - %kernel.root_dir%/../web/data/partials/sidebar-right/chat.json
            output: data/partials/sidebar-right/chat.json    
        profile_json:    
            inputs:
                - %kernel.root_dir%/../web/data/partials/sidebar-right/profile.json
            output: data/partials/sidebar-right/profile.json
        dashboardhtml:    
            inputs:
                - %kernel.root_dir%/../web/views/dashboard.html
            output: /views/dashboard.html
        matriculashtml:    
            inputs:
                - %kernel.root_dir%/../web/views/matriculas.html
            output: /views/matriculas.html
            
            

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Multiservices\ArxisBundle\Entity\Usuario
    registration:
        form:
            type: app_user_registration
    group:
        group_class: Multiservices\ArxisBundle\Entity\Grupo
