# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
     my_user_provider.class: AppBundle\Security\Core\User\FOSUBUserProvider

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    twig.extension.mes:
        class: AppBundle\Twig\Extension\MesExtension
        tags:
            - { name: twig.extension }      
    twig.extension.dia:
        class: AppBundle\Twig\Extension\DiaExtension
        tags:
            - { name: twig.extension }
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    fos_user.doctrine_registry:
        alias: doctrine
    #hwi_oauth.user.provider.entity:
    #    class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider    
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments: ['@fos_user.user_manager', { multiacademico: username }]    