doctrine:
    dbal:
       types:
           ClientesType: Multiservices\PayPayBundle\Form\Type\ClientesType
           FormasPagosType: Multiservices\PayPayBundle\Form\Type\FormasPagosType
           UsuariosType: Multiservices\PayPayBundle\Form\Type\UsuariosType             