<?php

namespace MultiacademicoBundle\Repository;

/**
 * ActividadAcademicaDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadAcademicaDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
