<?php

namespace MultiacademicoBundle\Repository;

/**
 * ActividadAcademicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadAcademicaRepository extends \Doctrine\ORM\EntityRepository
{
}
