<?php

namespace MultiacademicoBundle\Repository;

/**
 * PensionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PensionesRepository extends \Doctrine\ORM\EntityRepository
{
}
