<?php

namespace MultiacademicoBundle\Repository;

/**
 * RepresentantesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentantesRepository extends \Doctrine\ORM\EntityRepository
{
}
