<?php

namespace MultiacademicoBundle\Entity;

/**
 * AreaAcademicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaAcademicaRepository extends \Doctrine\ORM\EntityRepository
{
    public function materiasDeAreaAcademicaEnAula(Aula $aula, AreaAcademica $areaAcademica) {
        return $this->getEntityManager()->createQueryBuilder()
                ->select('materias')
                ->from('MultiacademicoBundle:Materias','materias')
                ->join('materias.distributivos','distributivos')
                ->join('distributivos.aula','aula')
                ->where(':areaAcademica MEMBER OF materias.areas AND aula=:aula')
                ->setParameters([
                    'areaAcademica'=>$areaAcademica,
                    'aula'=>$aula
                ])
                ->getQuery()
                ->getResult();
    }   
}
