<?php

namespace MultiacademicoBundle\Entity;

/**
 * AreaAcademicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaAcademicaRepository extends \Doctrine\ORM\EntityRepository
{
}
