MultiacademicoAnnotations:
    resource: "@MultiacademicoBundle/Controller/"
    type:     annotation
multiacademico_aulas:
    resource: "@MultiacademicoBundle/Resources/config/routing/aulas.yml"
multiacademico_matriculas:
    resource: "@MultiacademicoBundle/Resources/config/routing/matriculas.yml"
    #prefix:   /matriculas    
reportes:
    type: rest
    resource: MultiacademicoBundle\Controller\ReportesController
    options:
        expose: true
    prefix: api
miscalificaciones:
    type: rest
    resource: MultiacademicoBundle\Controller\MisCalificacionesController
    options:
        expose: true
    prefix: api 
multiacademico_comportamiento:
    resource: "@MultiacademicoBundle/Resources/config/routing/comportamiento.yml"
multiacademico_estadisticas:
    resource: "@MultiacademicoBundle/Resources/config/routing/estadisticas.yml"    
multiacademico_pension:
    resource: "@MultiacademicoBundle/Resources/config/routing/pension.yml"    
    #prefix:   /pension    
multiacademico_representantes:
    resource: "@MultiacademicoBundle/Resources/config/routing/representantes.yml"
    #prefix:   /representantes
multiacademico_actividadacademica:
    resource: "@MultiacademicoBundle/Resources/config/routing/actividadacademica.yml"
multiacademico_actividadacademicadetalle:
    resource: "@MultiacademicoBundle/Resources/config/routing/actividadacademicadetalle.yml"