MultiacademicoAnnotations:
    resource: "@MultiacademicoBundle/Controller/"
    type:     annotation
aulas:
    path:      /aulas/{page}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    requirements:
         page: ".*"
aulasapi:
    type: rest
    resource: MultiacademicoBundle\Controller\AulasController
    options:
        expose: true
    prefix: api
multiacademico_matriculas:
    resource: "@MultiacademicoBundle/Resources/config/routing/matriculas.yml"
    #prefix:   /matriculas    
reportes:
    type: rest
    resource: MultiacademicoBundle\Controller\ReportesController
    options:
        expose: true
    prefix: api
miscalificaciones:
    type: rest
    resource: MultiacademicoBundle\Controller\MisCalificacionesController
    options:
        expose: true
    prefix: api 
estadisticas:
    type: rest
    resource: MultiacademicoBundle\Controller\EstadisticasController
    options:
        expose: true
    prefix: api       