MultiacademicoAnnotations:
    resource: "@MultiacademicoBundle/Controller/"
    type:     annotation
aulas:
    type: rest
    resource: MultiacademicoBundle\Controller\AulasController
    options:
        expose: true
    prefix: api
reportes:
    type: rest
    resource: MultiacademicoBundle\Controller\ReportesController
    options:
        expose: true
    prefix: api
miscalificaciones:
    type: rest
    resource: MultiacademicoBundle\Controller\MisCalificacionesController
    options:
        expose: true
    prefix: api 
estadisticas:
    type: rest
    resource: MultiacademicoBundle\Controller\EstadisticasController
    options:
        expose: true
    prefix: api       