services:
#    multiacademico.example:
#        class: MultiacademicoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    validator.multiacademico.MatriculaValidator:
        class:  MultiacademicoBundle\Validator\Constraints\MatriculaValidator
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: matricula.validator }
    validator.multiacademico.DistributivoValidator:
        class:  MultiacademicoBundle\Validator\Constraints\DistributivoValidator
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: distributivo.validator }        

    multiacademico.estudiantes:
        class: MultiacademicoBundle\Datatables\EstudiantesDatatable
        tags:
            - { name: sg.datatable.view }
    multiacademicobundle_datatable.matriculas:
        class: MultiacademicoBundle\Datatables\MatriculasDatatable
        tags:
            - { name: sg.datatable.view }
    multiacademico.distributivos:
        class: MultiacademicoBundle\Datatables\DistributivosDatatable
        tags:
            - { name: sg.datatable.view }        
    multiacademico.pensiones:
        class: MultiacademicoBundle\Datatables\PensionDatatable
        tags:
            - { name: sg.datatable.view }                
    multiacademico.form.type.nota:
        class: MultiacademicoBundle\Form\Type\NotaType
        tags:
            - { name: form.type, alias: nota }  
      
    security.access.distributivo_voter : 
        class :       MultiacademicoBundle\Security\Authorization\Voter\DistributivoVoter 
        public :      false 
        tags : 
            -  {  name :  security.voter  }
    security.access.proyectosescolares_voter : 
        class :       MultiacademicoBundle\Security\Authorization\Voter\ProyectosEscolaresVoter 
        public :      false 
        tags : 
            -  {  name :  security.voter  }
    calificaciones.listener:
        class: MultiacademicoBundle\EventListener\CalificacionesListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
           # - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
            - { name: doctrine.event_listener, event: postFlush, method: postFlush }
            
    
