services:
#    multiacademico.example:
#        class: MultiacademicoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    multiacademico.estudiantes:
        class: MultiacademicoBundle\Datatables\EstudiantesDatatable
        tags:
            - { name: sg.datatable.view }
    multiacademico.distributivos:
        class: MultiacademicoBundle\Datatables\DistributivosDatatable
        tags:
            - { name: sg.datatable.view }        
    multiacademico.form.type.nota:
        class: MultiacademicoBundle\Form\Type\NotaType
        tags:
            - { name: form.type, alias: nota }           