services:
#    multiacademico.example:
#        class: MultiacademicoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    multiacademico.estudiantes:
        class: MultiacademicoBundle\Datatables\EstudiantesDatatable
        tags:
            - { name: sg.datatable.view }
    multiacademico.distributivos:
        class: MultiacademicoBundle\Datatables\DistributivosDatatable
        tags:
            - { name: sg.datatable.view }        
    multiacademico.form.type.nota:
        class: MultiacademicoBundle\Form\Type\NotaType
        tags:
            - { name: form.type, alias: nota }  
    security.access.distributivo_voter : 
        class :       MultiacademicoBundle\Security\Authorization\Voter\DistributivoVoter 
        public :      false 
        tags : 
            -  {  name :  security.voter  }
    security.access.proyectosescolares_voter : 
        class :       MultiacademicoBundle\Security\Authorization\Voter\ProyectosEscolaresVoter 
        public :      false 
        tags : 
            -  {  name :  security.voter  }
    calificaciones.listener:
        class: MultiacademicoBundle\EventListener\CalificacionesListener
        arguments: ['@service_container']
        tags:
            #- { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.event_listener, event: preUpdate, method: preUpdate }
            - { name: doctrine.orm.event_listener, event: postFlush, method: postFlush }
            
    