services:
#    multiacademico.example:
#        class: MultiacademicoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    entidadData:
        class: MultiacademicoBundle\Servicios\EntidadData
        arguments: ['@doctrine.orm.entity_manager']
    twig.extension.entidad:
        class: MultiacademicoBundle\Twig\Extension\EntidadExtension
        arguments: ['@entidadData']
        tags:
            - { name: twig.extension }    
    validator.multiacademico.MatriculaValidator:
        class:  MultiacademicoBundle\Validator\Constraints\MatriculaValidator
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: matricula.validator }
    validator.multiacademico.DistributivoValidator:
        class:  MultiacademicoBundle\Validator\Constraints\DistributivoValidator
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: distributivo.validator }        
    validator.multiacademico.EstudianteEmailValidator:
        class:  MultiacademicoBundle\Validator\Constraints\EstudianteEmailValidator
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: estudiante_email.validator }                
    validator.multiacademico.DocenteEmailValidator:
        class:  MultiacademicoBundle\Validator\Constraints\DocenteEmailValidator
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: docente_email.validator }        

    multiacademico.estudiantes:
        class: MultiacademicoBundle\Datatables\EstudiantesDatatable
        parent: sg_datatables.datatable.abstract
    multiacademico.docentes:
        class: MultiacademicoBundle\Datatables\DocentesDatatable
        parent: sg_datatables.datatable.abstract    
    multiacademicobundle_datatable.matriculas:
        class: MultiacademicoBundle\Datatables\MatriculasDatatable
        parent: sg_datatables.datatable.abstract
    multiacademicobundle_datatable.representantes:
        class: MultiacademicoBundle\Datatables\RepresentantesDatatable
        parent: sg_datatables.datatable.abstract
    multiacademico.aulas:
        class: MultiacademicoBundle\Datatables\AulaDatatable
        parent: sg_datatables.datatable.abstract
    multiacademico.distributivos:
        class: MultiacademicoBundle\Datatables\DistributivosDatatable
        parent: sg_datatables.datatable.abstract
    multiacademico.pensiones:
        class: MultiacademicoBundle\Datatables\PensionDatatable
        parent: sg_datatables.datatable.abstract
    multiacademico.form.type.nota:
        class: MultiacademicoBundle\Form\Type\NotaType
        tags:
            - { name: form.type, alias: nota }  

    security.access.distributivo_voter : 
        class :       MultiacademicoBundle\Security\Authorization\Voter\DistributivoVoter 
        public :      false 
        tags : 
            -  {  name :  security.voter  }
    security.access.proyectosescolares_voter : 
        class :       MultiacademicoBundle\Security\Authorization\Voter\ProyectosEscolaresVoter 
        public :      false 
        tags : 
            -  {  name :  security.voter  }
    calificaciones.listener:
        class: MultiacademicoBundle\EventListener\CalificacionesListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
           # - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
            - { name: doctrine.event_listener, event: postFlush, method: postFlush }