parameters:
#    parameter_name: value
     timeago.timestamp: timestamp
services:
#    notify.example:
#        class: Multiservices\NotifyBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    timeago:
        class: Multiservices\NotifyBundle\TimerService\timeago
        arguments: ["%timeago.timestamp%"]
    notificador:
        class: Multiservices\NotifyBundle\Servicios\Notificador
        arguments: ["@doctrine.orm.entity_manager"]
    notificadorlisten:
        class: Multiservices\NotifyBundle\Servicios\NotificadorListen
        arguments: ["@doctrine.orm.entity_manager"]