parameters:
#    parameter_name: value
     timeago.timestamp: timestamp
services:
#    notify.example:
#        class: Multiservices\NotifyBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    timeago:
        class: Multiservices\NotifyBundle\TimerService\timeago
        arguments: ["%timeago.timestamp%"]