<?php

namespace Multiservices\PayPayBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Multiservices\PayPayBundle\DBAL\Types\EstadoFacturaType;
use MultiacademicoBundle\Entity\Representantes;

/**
 * FacturasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturasRepository extends EntityRepository
{
    public function facturasPendientes($representante)
        {

           return $this->getEntityManager()
            ->createQueryBuilder()->select('f')
                    ->from('PayPayBundle:Facturas','f')
                    //->innerJoin('p.factura', 'f')
                    ->where('f.idcliente= :cliente AND (f.estado =:estado1 OR f.estado =:estado2)')
                    ->setParameter('cliente',  $representante)
                    ->setParameter('estado1',  EstadoFacturaType::NOPAGADA)
                    ->setParameter('estado2',   EstadoFacturaType::VENCIDA)
                   // ->getQuery()->getResult()
                    ;
        }
}
