<?php

namespace Multiservices\PayPayBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Multiservices\PayPayBundle\DBAL\Types\EstadoFacturaType;
use MultiacademicoBundle\Entity\Representantes;

/**
 * FacturasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturasRepository extends EntityRepository
{
    public function facturasPendientes($representante,$facturas=null)
        {
            $orw="";
            $params=['cliente'=>  $representante,
                       'estado1'=>  EstadoFacturaType::NOPAGADA,
                       'estado2'=>   EstadoFacturaType::VENCIDA];
            foreach ($facturas as $i=>$factura)
                {
                    ($i>0)?$orw.=" OR ":$orw.="";
                    $orw.=" f.id=:factura$i ";
                    $params["factura$i"]=$factura;
                }
           $qb=$this->getEntityManager()
            ->createQueryBuilder()->select('f')
                    ->from('PayPayBundle:Facturas','f')
                    //->innerJoin('p.factura', 'f')
                    ->where('f.idcliente= :cliente AND (f.estado =:estado1 OR f.estado =:estado2)')
                    ->setParameters($params);
           if ($orw!=""){
               $qb->orWhere($orw);
           }
           return $qb;
        }
}
