#rutas del back o api
pensiones_api:
    type: rest
    resource: Multiservices\PayPayBundle\Controller\PensionesController
    options:
        expose: true
    prefix: api
#ruta para txtbanco
pensiones_download:
    path:      /pensiones/download/{id}
    defaults:  { _controller: PayPayBundle:Pensiones:download}
    requirements:
        id: \d+
#para rutas front pensiones
pensiones:
    path:      /pensiones/{page}
    defaults:  { _controller: PayPayBundle:Pensiones:index, page: index}
    requirements:
         page: ".*"
